### ISSUE TITLE
Could you share me, what have you successfully to install macOS on your t1700?

### ISSUE THREAD

**Issue by abhisit** [hfutxqd/T1700-Hackintosh#1]
Hi,

I would like to install macOS on my Dell precision t1700.  Could you share me, what have you successfully to install macOS on your t1700?

Thank you so much,
Abhisit.

**Comment by fishand73** [comment]
macOS 10.13.4 High Sierra works fine.

**Comment by abhisit** [comment]
I spend my couple days to find the link to download macOS 10.13.4 and could not find it!  What the link do you used to download and could you tell me, please.

**Comment by fishand73** [comment]
https://pan.baidu.com/s/1JnN9mjGZOITStAV_avkQcA
